// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2MzZczPFwVGLMzNGaTfq-htxCxSWBa2Q',
    appId: '1:534802650722:web:143aaa459bbe6e2cb3e33b',
    messagingSenderId: '534802650722',
    projectId: 'destigo-caa22',
    authDomain: 'destigo-caa22.firebaseapp.com',
    storageBucket: 'destigo-caa22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCajwdp8Pn4WizNhbfj99HQi3lfra6G0uY',
    appId: '1:534802650722:android:47936d267772e857b3e33b',
    messagingSenderId: '534802650722',
    projectId: 'destigo-caa22',
    storageBucket: 'destigo-caa22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWVbNZi4wdgGNy6Z379TO9-Q2CcjotqMw',
    appId: '1:534802650722:ios:e6aba20c92a993e8b3e33b',
    messagingSenderId: '534802650722',
    projectId: 'destigo-caa22',
    storageBucket: 'destigo-caa22.appspot.com',
    iosBundleId: 'com.example.destiGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWVbNZi4wdgGNy6Z379TO9-Q2CcjotqMw',
    appId: '1:534802650722:ios:e6aba20c92a993e8b3e33b',
    messagingSenderId: '534802650722',
    projectId: 'destigo-caa22',
    storageBucket: 'destigo-caa22.appspot.com',
    iosBundleId: 'com.example.destiGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2MzZczPFwVGLMzNGaTfq-htxCxSWBa2Q',
    appId: '1:534802650722:web:9819b6972dd7ee81b3e33b',
    messagingSenderId: '534802650722',
    projectId: 'destigo-caa22',
    authDomain: 'destigo-caa22.firebaseapp.com',
    storageBucket: 'destigo-caa22.appspot.com',
  );
}
